blank_issues_enabled: false
contact_links:
  - name: üí¨ GitHub Discussions
    url: https://github.com/ViktorPro1/webstart-studio-react-app/discussions
    about: –û–±–≥–æ–≤–æ—Ä—ñ—Ç—å —ñ–¥–µ—ó –∑—ñ —Å–ø—ñ–ª—å–Ω–æ—Ç–æ—é
  - name: üìß Email Support
    url: mailto:webstartstudio978@gmail.com
    about: –ü—Ä–∏–≤–∞—Ç–Ω—ñ –ø–∏—Ç–∞–Ω–Ω—è
